resources:
  - repo: self
pool:
  vmImage: windows-latest
workspace:
  clean: all
name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: 
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
    - readme.md
    - Tests/*
variables: 
  Name: tag-git-release
steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageAzureDevOpsExtension@3
  displayName: 'Package Extension: $(Name)'
  inputs:
    extensionVisibility: public
    extensionPricing: free
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: 'liquorichris.$(Name)*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'